CREATE PROCEDURE GET_SINGLE_CUSTOMERINFO
(
   P_ID IN INTEGER,
   P_AGE OUT INTEGER,
   P_OCCUPATION OUT VARCHAR2,
   P_LASTSTATEMENTBALANCE OUT FLOAT
)
AS
BEGIN
   SELECT AGE, OCCUPATION, LASTSTATEMENTBALANCE INTO P_AGE, P_OCCUPATION, 
          P_LASTSTATEMENTBALANCE 
   FROM CROSSSELLCUSTOMERS 
   WHERE CROSSSELLCUSTOMERS.ID = P_ID;
END;