create table usuario
(
  cedula varchar2(10) not null,
  nombre varchar2(50) not null,
  direccion varchar2(100),
  puede_prestamo char check (puede_prestamo in (0,1)) not null,
  constraint usuario_pk primary key (cedula)
);
insert all
  into usuario (cedula, nombre, direccion, puede_prestamo) values ('0123456789', 'Azar Javed', 'Guarida Salamandra', 1)
  into usuario (cedula, nombre, direccion, puede_prestamo) values ('1234567890', 'Fringilla de Vigo', 'Capital del Imperio Nilfgaardiano', 1)
  into usuario (cedula, nombre, direccion, puede_prestamo) values ('0987654321', 'Borch Tres Grajos', 'Montañas de Zerrikania', 1)
  into usuario (cedula, nombre, direccion, puede_prestamo) values ('9876543210', 'Triss Merigold', 'Torre de Maribor', 1)
select * from dual;
create table autor
(
  id number generated always as identity,
  nombre varchar2(50) not null,
  constraint autor_pk primary key (id)
);
insert into autor (nombre) values ('Anónimo');
insert into autor (nombre) values ('Jaskier');
insert into autor (nombre) values ('Vesemir');
insert into autor (nombre) values ('Nenneke');
insert into autor (nombre) values ('Regis');
create table editorial
(
  id number generated always as identity,
  nombre varchar2(100) not null,
  constraint editorial_pk primary key (id)
);
insert into editorial (nombre) values ('Desconocida');
insert into editorial (nombre) values ('Universidad de Oxenfurt');
insert into editorial (nombre) values ('Kaer Morhen');
insert into editorial (nombre) values ('Santuario de Melitele');
insert into editorial (nombre) values ('Editorial del Ducado de Touissant');
create table libro
(
  id number generated always as identity,
  titulo varchar2(100) not null,
  autor_id number not null,
  constraint libro_pk primary key (id),
  constraint fk_autor foreign key (autor_id) references autor(id)
);
insert into libro (titulo, autor_id) values ('Vampiros: Hechos y Mitos', 5);
insert into libro (titulo, autor_id) values ('Espectros, Apariciones y Condenados', 3);
insert into libro (titulo, autor_id) values ('Plantas del Campo', 4);
insert into libro (titulo, autor_id) values ('Monstruos del Pantano', 3);
insert into libro (titulo, autor_id) values ('Sátira a la Profecía de Ithlinne', 1);
insert into libro (titulo, autor_id) values ('Balada del Lobo Blanco', 2);
insert into libro (titulo, autor_id) values ('Medicina Forense', 4);
alter session set NLS_DATE_FORMAT = 'DD-MM-YYYY';
create table edicion
(
  isbn varchar2(13) not null,
  libro_id number not null,
  editorial_id number not null,
  numero number(2) not null,
  fecha date,
  descripcion varchar2(200),
  constraint edicion_pk primary key (isbn),
  constraint fk_libro foreign key (libro_id) references libro(id),
  constraint fk_editorial foreign key (editorial_id) references editorial(id)
);
insert all
  into edicion (isbn, libro_id, editorial_id, numero, fecha, descripcion) values ('1111111111111', 1, 1, 1, '01-04-1112', 'Pergaminos, Lengua Antigua')
  into edicion (isbn, libro_id, editorial_id, numero, fecha, descripcion) values ('2222222222222', 1, 5, 2, '02-07-1216', 'Encuadernado, Traducido a Lengua Común, Incluye 8 nuevos mitos')
  into edicion (isbn, libro_id, editorial_id, numero, fecha, descripcion) values ('3333333333333', 5, 1, 1, '22-11-1019', 'Pergaminos, Lengua Élfica')
  into edicion (isbn, libro_id, editorial_id, numero, fecha, descripcion) values ('4444444444444', 2, 3, 1, '06-04-1212', 'Encuadernado, Lengua Común')
  into edicion (isbn, libro_id, editorial_id, numero, fecha, descripcion) values ('5555555555555', 3, 4, 1, '07-05-1213', 'Encuadernado, Lengua Común')
  into edicion (isbn, libro_id, editorial_id, numero, fecha, descripcion) values ('6666666666666', 4, 3, 1, '12-09-1219', 'Encuadernado, Lengua Común')
  into edicion (isbn, libro_id, editorial_id, numero, fecha, descripcion) values ('7777777777777', 6, 2, 1, '11-12-1222', 'Encuadernado, Lengua Común')
  into edicion (isbn, libro_id, editorial_id, numero, fecha, descripcion) values ('8888888888888', 7, 4, 1, '08-12-1211', 'Encuadernado, Lengua Antigua')
  into edicion (isbn, libro_id, editorial_id, numero, fecha, descripcion) values ('9999999999999', 7, 4, 2, '09-11-1223', 'Encuadernado, Traducido a Lengua Común')
select * from dual;
create table planta
(
  id number generated by default as identity,
  nombre varchar2(50) not null,
  constraint planta_pk primary key (id)
);
insert into planta (nombre) values ('Planta Baja');
insert into planta (nombre) values ('1er Piso');
insert into planta (nombre) values ('2do Piso');
create table estante
(
  planta_id number not null,
  id number not null,
  nombre varchar2(50) not null,
  constraint estante_pk primary key (planta_id, id),
  constraint fk_planta foreign key (planta_id) references planta(id)
);
insert into estante (planta_id, id, nombre) values (1, 1, 'Estante A');
insert into estante (planta_id, id, nombre) values (1, 2, 'Estante B');
insert into estante (planta_id, id, nombre) values (2, 1, 'Estante C');
insert into estante (planta_id, id, nombre) values (3, 1, 'Estante D');
create table ejemplar
(
  edicion_isbn varchar2(13) not null,
  id number not null,
  planta_id number not null,
  estante_id number not null,
  prestado char check (prestado in (0,1)) not null,
  observaciones varchar2(200),
  constraint ejemplar_pk primary key (edicion_isbn, id),
  constraint fk_edicion foreign key (edicion_isbn) references edicion(isbn),
  constraint fk_planta_estante foreign key (planta_id, estante_id) references estante(planta_id, id)
);
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('1111111111111', 1, 0, 1, 1, ' ');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('1111111111111', 2, 0, 1, 1, 'Arrugado');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('2222222222222', 1, 0, 1, 1, ' ');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('2222222222222', 2, 0, 1, 1, 'Falta Página 10');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('3333333333333', 1, 0, 1, 2, ' ');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('3333333333333', 2, 0, 1, 2, 'Rasgado');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('4444444444444', 1, 0, 1, 2, ' ');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('4444444444444', 2, 0, 2, 1, 'Portada Mutilada');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('5555555555555', 1, 0, 2, 1, 'Faltan Páginas 12 y 45');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('5555555555555', 2, 0, 2, 1, ' ');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('6666666666666', 1, 0, 2, 1, 'Rayada la Kikimora en la página 34');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('7777777777777', 1, 0, 3, 1, ' ');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('8888888888888', 1, 0, 3, 1, 'Portada Mutilada');
insert into ejemplar (edicion_isbn, id, prestado, planta_id, estante_id, observaciones) values ('9999999999999', 1, 0, 3, 1, ' ');
alter session set NLS_TIMESTAMP_FORMAT = 'DD-MM-YYYY HH24:MI:SS';
create table alquiler
(
  usuario_cedula varchar2(100) not null,
  edicion_isbn varchar2(13) not null,
  ejemplar_id number not null,
  fecha_hora_prestamo timestamp(0) not null,
  fecha_hora_estimada_entrega timestamp(0) not null,
  fecha_hora_entrega timestamp(0),
  constraint alquiler_pk primary key (usuario_cedula , ejemplar_id, fecha_hora_prestamo),
  constraint fk_usuario foreign key (usuario_cedula) references usuario(cedula),
  constraint fk_ejemplar foreign key (edicion_isbn, ejemplar_id) references ejemplar(edicion_isbn, id)
);
insert into alquiler(usuario_cedula, edicion_isbn, ejemplar_id, fecha_hora_prestamo, fecha_hora_estimada_entrega) values ('0123456789', '1111111111111', 1, '27-12-2019 09:10:02', '28-12-2019 00:00:00');
update ejemplar set prestado = 1 where edicion_isbn = '1111111111111' and id = 1;
insert into alquiler(usuario_cedula, edicion_isbn, ejemplar_id, fecha_hora_prestamo, fecha_hora_estimada_entrega) values ('0123456789', '2222222222222', 2, '27-12-2019 09:10:02', '28-12-2019 00:00:00');
update ejemplar set prestado = 1 where edicion_isbn = '2222222222222' and id = 2;
update usuario set puede_prestamo = 0 where cedula = '0123456789';
insert into alquiler(usuario_cedula, edicion_isbn, ejemplar_id, fecha_hora_prestamo, fecha_hora_estimada_entrega) values ('0987654321', '7777777777777', 1, '27-12-2019 11:00:23', '28-12-2019 12:30:00');
update ejemplar set prestado = 1 where edicion_isbn = '7777777777777' and id = 1;
update usuario set puede_prestamo = 0 where cedula = '0987654321';
update alquiler set fecha_hora_entrega = '28-12-2019 11:30:00' where usuario_cedula = '0987654321' and fecha_hora_prestamo = '27-12-2019 11:00:23';
update usuario set puede_prestamo = 1 where cedula = '0987654321';